### ISSUE TITLE
Less Support

### ISSUE THREAD

**Issue by lewiscowper** [animade/frontend-md#10]
I'd love to add this to our internal styleguide, but we use Less instead of SASS.

I see it's on your roadmap, I just thought I'd add an Issue for visibility and so anyone else can voice any opinions or that they would also like this.

**Comment by crismanNoble** [comment]
There is a pull request open for adding less support:

https://github.com/animade/frontend-md/pull/9

**Comment by CREEATION** [comment]
There's already a [pull request](https://github.com/animade/frontend-md/pull/9) for this! :)

**Comment by lewiscowper** [comment]
I checked when I made the issue and it wasn't there, but excellent news. :+1:

**Comment by brunowego** [comment]
+1

**Comment by jameschambers** [comment]
Closed by https://github.com/animade/frontend-md/commit/310d0d81bd68bf3bd30563ada219e568e4c31c17. Thanks @crismanNoble for the patch!
