### ISSUE TITLE
Postinstall script fails on Windows

### ISSUE THREAD

**Issue by davguij** [animade/frontend-md#3]
The postinstall command `chmod u+x app.js` fails on Windows as there's no `chmod` in Win systems.
There might be a way of executing the command only on *nix based systems?

**Comment by easingthemes** [comment]
Run with full path, eg

```
C:/Users/username/AppData/Roaming/npm/node_modules/frontend-md/app.js
```

This worked for me, although installation failed because of `chmod` postinstall. So for **win** you maybe don't need `chmod`.

**Comment by thedaviddias** [comment]
I have the same issue... I can put directly on "/AppData/Roaming/npm/" the package, but it's not the best way...

**Comment by nblackburn** [comment]
Also getting this problem

**Comment by shash7** [comment]
Any idea how to install this manually?
