### ISSUE TITLE
Parse .sass comments

### ISSUE THREAD

**Issue by rmasoni** [animade/frontend-md#6]
Frontend.md doesn't seem to be parsing `.sass` comments, which start with `//`.

I noticed you have something going on [here](https://github.com/animade/frontend-md/blob/master/lib/filetree.js#L127) but I lack the competence to debug and eventually fix or implement that myself.

**Comment by CREEATION** [comment]
It does work, however the parser doesn't parse `.sass` files, only `.scss`.
I already created a [pull request](https://github.com/animade/frontend-md/pull/4) for this.

**Comment by rmasoni** [comment]
Nice! Thank you!
